version: '3'

services:
  postgres:
    image: postgres:13.13-alpine3.18
    container_name: postgres
    env_file: app.env
    environment:
      POSTGRES_USER: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  go-project:
    container_name: go-project
    build: .
    env_file: app.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: